### ISSUE TITLE
Read a Log file failed!

### ISSUE THREAD

**Issue by THBTX** [Xanthos-Eve/vintel#118]
Somehow, I changed something on my PC, and now receive the following:
http://puu.sh/q4Zh8/b7c0e621e1.png and then when I OK that:
http://puu.sh/q4Zcz/b501e645fc.png
None of my toons are available in the dropdown.
I know it was something I did to my PC (while trying to network it with another PC on my local network).  I removed the Eve Client, and reinstalled, hoping this would help, but it has not.  Any help appreciated.
THB

**Comment by Xanthos-Eve** [comment]
The first dialog is part of the new user experience and is being displayed
because vintel failed to find its settings. This was due to you removing
the directory. To get things working vintel needs to know where to find eve
chat logs. Please refer to the readme for more detail (
https://github.com/Xanthos-Eve/vintel).

**Comment by Xanthos-Eve** [comment]
User issue - closing.
